s9

diff --git a/.github/workflows/status-check.yml b/.github/workflows/status-check.yml
--- a/.github/workflows/status-check.yml
+++ b/.github/workflows/status-check.yml
@@ -4,7 +4,7 @@ on: [push]
 
 jobs:
   job1:
-    runs-on: ubunut-latest
+    runs-on: ubuntu-latest
     steps:
       - name: Fail
         run: exit 1
@@ -15,7 +15,7 @@ jobs:
         if: success()
         run: echo "Runs on Succes"
       - name: Always Runs
-        if: always()  # if: success() || failure()
+        if: always()  # if: success() || failure()1
         run: echo "Always Runs"
       - name: Runs when Cancelled
         if: cancelled()
